fix(translations): fix text translations after language change
OpenSprinkler/OpenSprinkler-App pull request #181
Opened 2024-12-05 23:49 UTC by mellodev

⚠️ WORK IN PROGRESS

#### Changes Proposed

- Attempt to fix the issue where localizations are not properly applied due to the timing in which the components are rendered. 
- Logs: refactor the "View Logs" logic from ui-dom into `OSApp.Logs.displayPage()`
- Current Weather: WIP

#### Demo Video or Screenshots

Please include a short video or screenshot(s) to assist with pr review

2024-12-21 16:11 UTC, salbahra requested changes

2024-12-21 16:11 UTC, salbahra commented on www/js/modules/about.js
> +	var page = $( "<div data-role='page' id='about'>" +
Any chance we can fix the indentations/nesting of the HTML here?

2024-12-21 16:11 UTC, salbahra commented on www/js/modules/dashboard.js
> +	var page = $( "<div data-role='page' id='sprinklers'>" +
Same comment, any chance we can restore the indentation? Hard to read without it. Can use a template string if it's easier.

2024-12-21 16:11 UTC, salbahra commented on www/js/modules/logs.js
> +	var page = $( "<div data-role='page' id='logs'>" +
Same thing here (indentation)

2024-12-21 16:11 UTC, salbahra commented on www/js/modules/programs.js
> +	var page = $( "<div data-role='page' id='manual'>" +
Same here please.

2024-12-21 16:11 UTC, salbahra commented on www/js/modules/programs.js
> +	var page = $( "<div data-role='page' id='preview'>" +
And here :)

2025-01-07 18:59 UTC, mellodev commented
Great catch, thanks for reviewing. Please take another look, the page templates have been updated.

2025-01-07 19:02 UTC, merged